LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(call all-subdir-java-files)
LOCAL_MODULE := Cling
LOCAL_AAPT_FLAGS := --auto-add-overlay
LOCAL_STATIC_JAVA_LIBRARIES += http-2.2.1
LOCAL_STATIC_JAVA_LIBRARIES += httpcore-4.2.3
LOCAL_STATIC_JAVA_LIBRARIES += javax.annotation_1.0
LOCAL_STATIC_JAVA_LIBRARIES += javax.inject
LOCAL_STATIC_JAVA_LIBRARIES += javax.servlet-3.0.0.v201103241009
LOCAL_STATIC_JAVA_LIBRARIES += jetty-client-8.1.9.v20130131
LOCAL_STATIC_JAVA_LIBRARIES += jetty-continuation-8.1.9.v20130131
LOCAL_STATIC_JAVA_LIBRARIES += jetty-http-8.1.9.v20130131
LOCAL_STATIC_JAVA_LIBRARIES += jetty-io-8.1.9.v20130131
LOCAL_STATIC_JAVA_LIBRARIES += jetty-security-8.1.9.v20130131
LOCAL_STATIC_JAVA_LIBRARIES += jetty-server-8.1.9.v20130131
LOCAL_STATIC_JAVA_LIBRARIES += jetty-servlet-8.1.9.v20130131
LOCAL_STATIC_JAVA_LIBRARIES += jetty-util-8.1.9.v20130131
LOCAL_STATIC_JAVA_LIBRARIES += seamless-http-1.1.1
LOCAL_STATIC_JAVA_LIBRARIES += seamless-util-1.1.1
LOCAL_STATIC_JAVA_LIBRARIES += seamless-xml-1.1.1
LOCAL_STATIC_JAVA_LIBRARIES += slf4j-api-1.6.1
LOCAL_STATIC_JAVA_LIBRARIES += slf4j-jdk14-1.6.1
LOCAL_STATIC_JAVA_LIBRARIES += httpclient-4.2.2
LOCAL_STATIC_JAVA_LIBRARIES += cdi-api
include $(BUILD_STATIC_JAVA_LIBRARY)

include $(LOCAL_PATH)/libs/Common.mk

